In [1]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import scipy.stats as stats
import statsmodels.stats
import math
from statsmodels.tsa.stattools import adfuller
import seaborn as sns
import itertools
from statsmodels.stats.stattools import durbin_watson

In [2]:
# import Data set + separate them into two Dataset -> Absolutevalues and Log
df=pd.read_csv('AQSDataLog.csv', sep=',')
df['Date'] = pd.to_datetime(df['Date']) # change to datetime
df.set_index('Date', inplace=True) #index 
df = df.rename(columns={'FTSE 100': 'FTSE_100', 'FTSE 100_log': 'FTSE_100_log'})
dflog = df.drop(['BTC','BCH','LTC', 'ETH','EUR', 'CHF', 'GBP', 'RUB', 'YEN', 'SEK', 'Gold', 'Silver','Palladium','Platinum','OIL',
                'MSCI', 'FTSE_100','NASDAQ','DAX', 'SMI'], axis=1)
dflog.dropna(inplace=True)

FileNotFoundError: [Errno 2] No such file or directory: 'AQSDataLog.csv'

In [3]:
# do we have NAN?
dflog.isna().sum()

BTC_log          0
BCH_log          0
LTC_log          0
ETH_log          0
EUR_log          0
CHF_log          0
GBP_log          0
RUB_log          0
YEN_log          0
SEK_log          0
Gold_log         0
Silver_log       0
Palladium_log    0
Platinum_log     0
OIL_log          0
MSCI_log         0
FTSE_100_log     0
NASDAQ_log       0
DAX_log          0
SMI_log          0
dtype: int64

In [4]:
dflog.describe()

,BTC_log,BCH_log,LTC_log,ETH_log,EUR_log,CHF_log,GBP_log,RUB_log,YEN_log,SEK_log,Gold_log,Silver_log,Palladium_log,Platinum_log,OIL_log,MSCI_log,FTSE_100_log,NASDAQ_log,DAX_log,SMI_log
count,778.000000,778.000000,778.000000,778.000000,778.000000,778.000000,778.000000,778.000000,778.000000,778.000000,778.000000,778.000000,778.000000,778.000000,778.000000,778.000000,778.000000,778.000000,778.000000,778.000000
mean,-0.002156,0.000184,-0.001365,-0.001819,-0.000097,0.000166,-0.000087,-0.000146,0.000124,0.000127,-0.000576,-0.000787,-0.000964,-0.000307,0.000304,-0.000371,0.000090,-0.000828,-0.000236,-0.000233
std,0.038484,0.059236,0.053987,0.049551,0.003355,0.003429,0.005058,0.007722,0.003970,0.004735,0.008059,0.017458,0.020702,0.015553,0.059699,0.011518,0.011615,0.013588,0.013110,0.009452
min,-0.157560,-0.437510,-0.267538,-0.276164,-0.014253,-0.018428,-0.026241,-0.085795,-0.031642,-0.035835,-0.036340,-0.079027,-0.181353,-0.097077,-0.574026,-0.083507,-0.086668,-0.058181,-0.079434,-0.068957
25%,-0.018132,-0.020438,-0.021968,-0.024372,-0.001326,-0.001209,-0.001910,-0.001988,-0.000927,-0.001512,-0.003628,-0.005878,-0.009078,-0.006183,-0.008556,-0.003644,-0.003383,-0.005675,-0.004220,-0.003710
50%,-0.001075,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.014844,0.021573,0.021945,0.017607,0.001081,0.001323,0.001817,0.002407,0.001197,0.001970,0.001565,0.002562,0.003034,0.004132,0.006323,0.001275,0.002766,0.001246,0.002364,0.001843
max,0.309314,0.451509,0.389435,0.410877,0.020646,0.014126,0.036939,0.045615,0.028513,0.020074,0.058927,0.162015,0.229765,0.138772,1.129042,0.102798,0.115124,0.091428,0.089808,0.099881

In [5]:
dflog.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 778 entries, 2020-12-31 to 2018-11-15
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   BTC_log        778 non-null    float64
 1   BCH_log        778 non-null    float64
 2   LTC_log        778 non-null    float64
 3   ETH_log        778 non-null    float64
 4   EUR_log        778 non-null    float64
 5   CHF_log        778 non-null    float64
 6   GBP_log        778 non-null    float64
 7   RUB_log        778 non-null    float64
 8   YEN_log        778 non-null    float64
 9   SEK_log        778 non-null    float64
 10  Gold_log       778 non-null    float64
 11  Silver_log     778 non-null    float64
 12  Palladium_log  778 non-null    float64
 13  Platinum_log   778 non-null    float64
 14  OIL_log        778 non-null    float64
 15  MSCI_log       778 non-null    float64
 16  FTSE_100_log   778 non-null    float64
 17  NASDAQ_log     778 non-null    float64
 18  DAX_log        778 non-null    float64
 19  SMI_log        778 non-null    float64
dtypes: float64(20)
memory usage: 127.6 KB

# Start with the Regressions

In [6]:
#unrelevant regression - just to get different values of OLS that can be included in final output
y = df['BTC_log']
x = df[['Gold', 'Silver','Palladium','Platinum','OIL','MSCI', 'FTSE_100','NASDAQ','DAX', 'SMI']]
x = sm.add_constant(x)
model = sm.OLS(y,x, missing = 'drop') 
results = model.fit()

#list all different values that the results object of an OLS can return to select for loop
dir(results)

['HC0_se',
 'HC1_se',
 'HC2_se',
 'HC3_se',
 '_HCCM',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abat_diagonal',
 '_cache',
 '_data_attr',
 '_data_in_cache',
 '_get_robustcov_results',
 '_is_nested',
 '_use_t',
 '_wexog_singular_values',
 'aic',
 'bic',
 'bse',
 'centered_tss',
 'compare_f_test',
 'compare_lm_test',
 'compare_lr_test',
 'condition_number',
 'conf_int',
 'conf_int_el',
 'cov_HC0',
 'cov_HC1',
 'cov_HC2',
 'cov_HC3',
 'cov_kwds',
 'cov_params',
 'cov_type',
 'df_model',
 'df_resid',
 'eigenvals',
 'el_test',
 'ess',
 'f_pvalue',
 'f_test',
 'fittedvalues',
 'fvalue',
 'get_influence',
 'get_prediction',
 'get_robustcov_results',
 'initialize',
 'k_constant',
 'llf',
 'load',
 'model',
 'mse_model',
 'mse_resid',
 'mse_total',
 'nobs',
 'normalized_cov_params',
 'outlier_test',
 'params',
 'predict',
 'pvalues',
 'remove_data',
 'resid',
 'resid_pearson',
 'rsquared',
 'rsquared_adj',
 'save',
 'scale',
 'ssr',
 'summary',
 'summary2',
 't_test',
 't_test_pairwise',
 'tvalues',
 'uncentered_tss',
 'use_t',
 'wald_test',
 'wald_test_terms',
 'wresid']

In [7]:
dflog.columns

Index(['BTC_log', 'BCH_log', 'LTC_log', 'ETH_log', 'EUR_log', 'CHF_log',
       'GBP_log', 'RUB_log', 'YEN_log', 'SEK_log', 'Gold_log', 'Silver_log',
       'Palladium_log', 'Platinum_log', 'OIL_log', 'MSCI_log', 'FTSE_100_log',
       'NASDAQ_log', 'DAX_log', 'SMI_log'],
      dtype='object')

In [8]:
target_variables = ['BTC', 'BCH', 'LTC', 'ETH', 'EUR', 'CHF', 'GBP', 'RUB', 'YEN', 'SEK']
target_variables_log = ['BTC_log', 'BCH_log', 'LTC_log', 'ETH_log','EUR_log', 'CHF_log', 'GBP_log', 'RUB_log', 'YEN_log', 'SEK_log']

x = df[['Gold', 'Silver','Palladium','Platinum','OIL','MSCI', 'FTSE_100','NASDAQ','DAX', 'SMI']]
x = sm.add_constant(x)

#x = df[['Gold_log', 'Silver_log', 'Palladium_log', 'Platinum_log', 'OIL_log', 'MSCI_log', 'FTSE_100_log', 'NASDAQ_log', 'DAX_log', 'SMI_log']]
#x = sm.add_constant(x)

explanatory_variables = x.columns

results_of_interest = []
for i in explanatory_variables: results_of_interest.append('params.'+i)
for i in explanatory_variables: results_of_interest.append('bse.'+i)
for i in explanatory_variables: results_of_interest.append('pvalues.'+i)    
    
results_of_interest.extend(('rsquared','rsquared_adj','aic','autocorrelation', 'heteroscedasticity_lm', 'heteroscedasticity_lm_pvalue'))#, 'multicollinearity'))

In [29]:
results_of_interest

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [10]:
# list/array with all regression combinations
regression_combinations = []

explanatory_variables = ['Gold', 'Silver','Palladium','Platinum','OIL','MSCI', 'FTSE_100','NASDAQ','DAX', 'SMI']
for n in range(0, len(explanatory_variables)+1):
    regression_combinations.extend(list(itertools.combinations(explanatory_variables, n)))

In [11]:
len(regression_combinations)

1024

In [33]:
#creation of all rows
rows = []
for asset in target_variables: 
    for i in range(1,len(regression_combinations)+1): rows.append(asset+str(i))
        
len(rows)

10240

In [13]:
# loop regression combination with rows

df_loop = pd.DataFrame(index=rows, columns=['y', 'x'])

for i in range(0,len(rows)):
    df_loop['y'][i] = target_variables[math.floor(i/len(regression_combinations))]
    df_loop['x'][i] = list(regression_combinations[int(math.remainder(i,len(regression_combinations)))])

df_loop

           y                                                  x
BTC1     BTC                                                 []
BTC2     BTC                                             [Gold]
BTC3     BTC                                           [Silver]
BTC4     BTC                                        [Palladium]
BTC5     BTC                                         [Platinum]
...      ...                                                ...
SEK1020  SEK  [Gold, Silver, Palladium, OIL, MSCI, FTSE_100,...
SEK1021  SEK  [Gold, Silver, Platinum, OIL, MSCI, FTSE_100, ...
SEK1022  SEK  [Gold, Palladium, Platinum, OIL, MSCI, FTSE_10...
SEK1023  SEK  [Silver, Palladium, Platinum, OIL, MSCI, FTSE_...
SEK1024  SEK  [Gold, Silver, Palladium, Platinum, OIL, MSCI,...

[10240 rows x 2 columns]

# Regression Test -> abolute pricing

#create empfty dataframe to fill during the loop
output_table = pd.DataFrame(index=rows, columns=results_of_interest)

#loop with regression of each asset over all 10 variables
for i in range(0,len(rows)):
        x = df[df_loop['x'][i]]
        x = sm.add_constant(x)
        y = df[df_loop['y'][i]]
        model = sm.OLS(y, x) 
        results = model.fit()

        for result in results_of_interest[:-3]:
            try: output_table[result][i] = eval("results."+result)
            except: pass

        output_table["autocorrelation"][i] = durbin_watson(results.resid)

        het = statsmodels.stats.diagnostic.het_breuschpagan(results.resid, exog_het = x)
        output_table["heteroscedasticity_lm"][i] = het[0]
        output_table["heteroscedasticity_lm_pvalue"][i] = het[1]

        #output_table["multicollinearity"][asset] = add function that returns multicollinearity


output_table

In [15]:
output_table.to_csv('output_table_absolut.csv')
output_table.head()

,params.const,params.Gold,params.Silver,params.Palladium,params.Platinum,params.OIL,params.MSCI,params.FTSE_100,params.NASDAQ,params.DAX,...,pvalues.FTSE_100,pvalues.NASDAQ,pvalues.DAX,pvalues.SMI,rsquared,rsquared_adj,aic,autocorrelation,heteroscedasticity_lm,heteroscedasticity_lm_pvalue
BTC1,8938.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,-2.22045e-16,-2.22045e-16,15194.7,0.00778187,-1.72973e-13,NaN
BTC2,-10591.2,12.5037,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.485274,0.484612,14679.3,0.0152745,58.9337,1.63074e-14
BTC3,-4919.82,NaN,763.613,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.509435,0.508803,14641.9,0.0195641,140.457,2.11526e-32
BTC4,-2375.97,NaN,NaN,6.18719,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.365398,0.364581,14842.4,0.0159204,57.5316,3.32588e-14
BTC5,-17910.9,NaN,NaN,NaN,30.9097,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.313433,0.31255,14903.7,0.0194913,89.6348,2.86438e-21

# Regression  -> Log

In [30]:
target_variables_log = ['BTC_log', 'BCH_log', 'LTC_log', 'ETH_log','EUR_log', 'CHF_log', 'GBP_log', 'RUB_log', 'YEN_log', 'SEK_log']

#x = df[['Gold', 'Silver','Palladium','Platinum','OIL','MSCI', 'FTSE_100','NASDAQ','DAX', 'SMI']]
##x = sm.add_constant(x)

x = df[['Gold_log', 'Silver_log', 'Palladium_log', 'Platinum_log', 'OIL_log', 'MSCI_log', 'FTSE_100_log', 'NASDAQ_log', 'DAX_log', 'SMI_log']]
x = sm.add_constant(x)

explanatory_variables = x.columns

results_of_interest_log = []
for i in explanatory_variables: results_of_interest_log.append('params.'+i)
for i in explanatory_variables: results_of_interest_log.append('bse.'+i)
for i in explanatory_variables: results_of_interest_log.append('pvalues.'+i)    
    
results_of_interest_log.extend(('rsquared','rsquared_adj','aic','autocorrelation', 'heteroscedasticity_lm', 'heteroscedasticity_lm_pvalue'))#, 'multicollinearity'))

In [17]:
results_of_interest_log

['params.const',
 'params.Gold_log',
 'params.Silver_log',
 'params.Palladium_log',
 'params.Platinum_log',
 'params.OIL_log',
 'params.MSCI_log',
 'params.FTSE_100_log',
 'params.NASDAQ_log',
 'params.DAX_log',
 'params.SMI_log',
 'bse.const',
 'bse.Gold_log',
 'bse.Silver_log',
 'bse.Palladium_log',
 'bse.Platinum_log',
 'bse.OIL_log',
 'bse.MSCI_log',
 'bse.FTSE_100_log',
 'bse.NASDAQ_log',
 'bse.DAX_log',
 'bse.SMI_log',
 'pvalues.const',
 'pvalues.Gold_log',
 'pvalues.Silver_log',
 'pvalues.Palladium_log',
 'pvalues.Platinum_log',
 'pvalues.OIL_log',
 'pvalues.MSCI_log',
 'pvalues.FTSE_100_log',
 'pvalues.NASDAQ_log',
 'pvalues.DAX_log',
 'pvalues.SMI_log',
 'rsquared',
 'rsquared_adj',
 'aic',
 'autocorrelation',
 'heteroscedasticity_lm',
 'heteroscedasticity_lm_pvalue']

In [31]:
# list/array with all regression combinations
regression_combinations_log = []

explanatory_variables_log = ['Gold_log', 'Silver_log','Palladium_log','Platinum_log','OIL_log','MSCI_log', 'FTSE_100_log','NASDAQ_log','DAX_log', 'SMI_log']
for n in range(0, len(explanatory_variables_log)+1):
    regression_combinations_log.extend(list(itertools.combinations(explanatory_variables_log, n)))

In [32]:
len(regression_combinations_log)

1024

In [20]:
target_variables_log

['BTC_log',
 'BCH_log',
 'LTC_log',
 'ETH_log',
 'EUR_log',
 'CHF_log',
 'GBP_log',
 'RUB_log',
 'YEN_log',
 'SEK_log']

In [22]:
# test without row_log

In [34]:
# loop regression combination with rows

df_loop = pd.DataFrame(index=rows, columns=['y', 'x'])

for i in range(0,len(rows)):
    df_loop['y'][i] = target_variables[math.floor(i/len(regression_combinations))]
    df_loop['x'][i] = list(regression_combinations[int(math.remainder(i,len(regression_combinations)))])

df_loop

           y                                                  x
BTC1     BTC                                                 []
BTC2     BTC                                             [Gold]
BTC3     BTC                                           [Silver]
BTC4     BTC                                        [Palladium]
BTC5     BTC                                         [Platinum]
...      ...                                                ...
SEK1020  SEK  [Gold, Silver, Palladium, OIL, MSCI, FTSE_100,...
SEK1021  SEK  [Gold, Silver, Platinum, OIL, MSCI, FTSE_100, ...
SEK1022  SEK  [Gold, Palladium, Platinum, OIL, MSCI, FTSE_10...
SEK1023  SEK  [Silver, Palladium, Platinum, OIL, MSCI, FTSE_...
SEK1024  SEK  [Gold, Silver, Palladium, Platinum, OIL, MSCI,...

[10240 rows x 2 columns]

In [35]:
df_loop_log = pd.DataFrame(index=rows, columns=['y', 'x'])

for i in range(0,len(rows)):
    df_loop_log['y'][i] = target_variables_log[math.floor(i/len(regression_combinations_log))]
    df_loop_log['x'][i] = list(regression_combinations_log[int(math.remainder(i,len(regression_combinations_log)))])

df_loop_log

               y                                                  x
BTC1     BTC_log                                                 []
BTC2     BTC_log                                         [Gold_log]
BTC3     BTC_log                                       [Silver_log]
BTC4     BTC_log                                    [Palladium_log]
BTC5     BTC_log                                     [Platinum_log]
...          ...                                                ...
SEK1020  SEK_log  [Gold_log, Silver_log, Palladium_log, OIL_log,...
SEK1021  SEK_log  [Gold_log, Silver_log, Platinum_log, OIL_log, ...
SEK1022  SEK_log  [Gold_log, Palladium_log, Platinum_log, OIL_lo...
SEK1023  SEK_log  [Silver_log, Palladium_log, Platinum_log, OIL_...
SEK1024  SEK_log  [Gold_log, Silver_log, Palladium_log, Platinum...

[10240 rows x 2 columns]

In [36]:
#create empfty dataframe to fill during the loop
output_table_log = pd.DataFrame(index=rows, columns=results_of_interest_log)

#loop with regression of each asset over all 10 variables
for i in range(0,len(rows)):
        x = dflog[df_loop_log['x'][i]]
        x = sm.add_constant(x)
        y = dflog[df_loop_log['y'][i]]
        model = sm.OLS(y, x, missing = 'drop') 
        results = model.fit()

        for result in results_of_interest_log[:-3]:
            try: output_table_log[result][i] = eval("results."+result)
            except: pass

        output_table_log["autocorrelation"][i] = durbin_watson(results.resid)

        het = statsmodels.stats.diagnostic.het_breuschpagan(results.resid, exog_het = x)
        output_table_log["heteroscedasticity_lm"][i] = het[0]
        output_table_log["heteroscedasticity_lm_pvalue"][i] = het[1]

        #output_table["multicollinearity"][asset] = add function that returns multicollinearity

In [37]:
output_table_log.to_csv('output_table_log.csv')
output_table_log.head()

,params.const,params.Gold_log,params.Silver_log,params.Palladium_log,params.Platinum_log,params.OIL_log,params.MSCI_log,params.FTSE_100_log,params.NASDAQ_log,params.DAX_log,...,pvalues.FTSE_100_log,pvalues.NASDAQ_log,pvalues.DAX_log,pvalues.SMI_log,rsquared,rsquared_adj,aic,autocorrelation,heteroscedasticity_lm,heteroscedasticity_lm_pvalue
BTC1,-0.00215573,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.22045e-16,2.22045e-16,-2859.84,2.12535,0,NaN
BTC2,-0.00152856,1.08956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0520612,0.0508397,-2899.44,2.14774,8.62467,0.0033164
BTC3,-0.00170766,NaN,0.569069,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0666484,0.0654456,-2911.5,2.13456,4.90048,0.0268492
BTC4,-0.00178198,NaN,NaN,0.387806,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0435223,0.0422898,-2892.46,2.14877,35.4358,2.63602e-09
BTC5,-0.00196817,NaN,NaN,NaN,0.610004,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0607813,0.059571,-2906.63,2.1306,31.5435,1.95026e-08

# Analysis of Output table

In [ ]:
df=pd.read_csv('output_table_log.csv', sep=';')
df.head()

# Rest ist trash

In [ ]:
target_variables_log = ['BTC_log', 'BCH_log', 'LTC_log', 'ETH_log','EUR_log', 'CHF_log', 'GBP_log', 'RUB_log', 'YEN_log', 'SEK_log']


x = dflog[['Gold_log', 'Silver_log', 'Palladium_log', 'Platinum_log', 'OIL_log', 'MSCI_log', 'FTSE_100_log', 'NASDAQ_log', 'DAX_log', 'SMI_log']]
x = sm.add_constant(x)

explanatory_variables = x.columns

results_of_interest_log = []
for i in explanatory_variables: results_of_interest_log.append('params.'+i)
for i in explanatory_variables: results_of_interest_log.append('bse.'+i)
for i in explanatory_variables: results_of_interest_log.append('pvalues.'+i)    
    
results_of_interest_log.extend(('rsquared','rsquared_adj','aic','autocorrelation', 'heteroscedasticity_lm', 'heteroscedasticity_lm_pvalue'))#, 'multicollinearity'))

In [ ]:
results_of_interest_log

In [ ]:
output_table_log.to_csv('output_table_log.csv')

In [ ]:
## alte Tabelle

In [ ]:
output_table.to_csv('output_table.csv')